---
service: petshop
functions:
- pets
- stores
- users
environments:
  production:
    ecr_registry: 123456789012.dkr.ecr.eu-west-1.amazonaws.com
  staging:
    ecr_registry: 210987654321.dkr.ecr.eu-west-1.amazonaws.com
  test:
    ecr_registry: 210987654321.dkr.ecr.eu-west-1.amazonaws.com
